# creating authentication deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: egs-doctalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-api
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
        - name: authentication-svc
          image: registry.deti:5000/egs-doctalk/egs-authentication-svc:v1
          ports:
            - containerPort: 5800
            
# creating authentication service
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-svc
  namespace: egs-doctalk
spec:
  selector:
    app: authentication-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5800
  type: ClusterIP

  # Configure Traefik ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentication-webapp-k3s
  namespace: egs-doctalk
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: app-egs-doctalk-auth.deti
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authentication-svc
            port: 
              number: 80
