# To build: docker buildx build --platform linux/amd64 --network=host -t registry.deti:5000/egs-doctalk/egs-authentication-svc:v1 -f authentication-service/Dockerfile.auth .
# To add to registry: docker push registry.deti:5000/egs-doctalk/egs-authentication-svc:v1

FROM node:alpine

LABEL maintainer="Jodionisio Muachifi"
LABEL ua="Universidade de Aveiro"
LABEL curso="MECT"
LABEL project="EGS-Agendamento de consultas Online"
LABEL service="Google,Facebook Authentication"

# Create app directory
RUN mkdir /auth-service
WORKDIR /authentication-service/auth-service

RUN apk update && apk upgrade && apk add --no-cache netcat-openbsd

# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./authentication-service/auth-service/package.json ./authentication-service/auth-service/package-lock.json ./
COPY ./authentication-service/auth-service/index.js  ./authentication-service/auth-service/public/  ./authentication-service/auth-service/.env ./auth-service/

RUN npm install 

# If you are building your code for production
# RUN npm ci --only=production

COPY ./authentication-service/auth-service .

EXPOSE 5800
ENTRYPOINT ["node", "index.js"]
